# Justfile for sillystrings project

set shell := ["bash", "-c"]

# Show available recipes
default:
    @just --list

# Initialize the development environment
install:
    uv sync
    uv run pre-commit install

# Run the CLI app locally. Usage: just run --help
run *args:
    uv run sillystrings {{args}}

# Run tests
test:
    uv run pytest

# Run tests with coverage and enforce 100% execution
test-cov:
    uv run pytest --cov --cov-fail-under=100

# Check code formatting (for CI)
format-check:
    uv run ruff format --check src/ tests/

# Format code
format:
    uv run ruff format src/ tests/

# Run linter without auto-fixing (for CI)
lint-check:
    uv run ruff check src/ tests/

# Run linter and auto-fix issues
lint:
    uv run ruff check --fix src/ tests/

# Run type checks
typecheck:
    uv run ty check src/

# Run all checks (format, lint, typecheck, tests with coverage)
check: format-check lint-check typecheck test-cov

# Clean up cache directories
clean:
    rm -rf .pytest_cache .ruff_cache
    find . -type d -name "__pycache__" -exec rm -rf {} +
    find . -type f -name "*.pyc" -delete

# Upgrade uv.lock and sync
lock-upgrade:
    #!/usr/bin/env bash
    set -euo pipefail

    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if [ "$BRANCH" = "main" ]; then
        TIMESTAMP=$(date +%s)
        NEW_BRANCH="chore/update-deps-$TIMESTAMP"
        echo "Creating new branch $NEW_BRANCH to protect main..."
        git checkout -b "$NEW_BRANCH"
    fi

    uv lock --upgrade
    uv sync

    if git diff --quiet pyproject.toml uv.lock; then
        echo "No dependencies to update."
        if [ "$BRANCH" = "main" ]; then
            git checkout main
            git branch -D "$NEW_BRANCH"
        fi
        exit 0
    fi

    git add pyproject.toml uv.lock
    git commit -m "chore: update dependencies"

    if [ "$BRANCH" = "main" ]; then
        echo "Pushing new dependency branch upstream..."
        git push -u origin "$NEW_BRANCH"

        echo "Creating Pull Request..."
        if command -v gh &> /dev/null && gh auth status &> /dev/null; then
            gh pr create \
                --title "chore: update dependencies" \
                --body "Automated PR to update uv.lock dependencies generated by \`just lock-upgrade\`." \
                --base main \
                --head "$NEW_BRANCH"
            echo "Pull Request created successfully."
        else
            echo "Warning: GitHub CLI (gh) is not installed or not authenticated."
            echo "Please install 'gh' and run 'gh auth login' to automatically create PRs."
            echo "You can manually create the PR here: https://github.com/jkomalley/sillystrings/pull/new/$NEW_BRANCH"
        fi
    fi

# Bump project version (usage: just bump-version <major|minor|patch|dev|beta|alpha|rc>)
bump-version part:
    uv version --bump {{part}}
