name: "Publish: TestPyPI"

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: astral-sh/setup-uv@v10.0.1

      - run: uv build

      - run: uv publish --publish-url https://test.pypi.org/legacy/
